/**
* Class Name: WhatsAppMessageBatchSchedulable
* Test Class: BroadcastMessageControllerTest
* Description: This class is used to schedule the batch process.
* Created Date: 03 April 2025
* Created By: Rachit Shah
*--------------------------------------------------------------------------------
**/

global with sharing class WhatsAppMessageBatchSchedulable  {
    //Its a global class and a part of a manage package so we can't remove it.
}